package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:43:41 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;


/**
 * DrugExposureRefId generated by hbm2java
 */

public class DrugExposureRefId  {


    // Fields    

     private String drugExposureType;
     private String drugExposureTypeDesc;
     private BigDecimal persistenceWindow;


    // Constructors

    /** default constructor */
    public DrugExposureRefId() {
    }

	/** minimal constructor */
    public DrugExposureRefId(String drugExposureType) {
        this.drugExposureType = drugExposureType;
    }
    
    /** full constructor */
    public DrugExposureRefId(String drugExposureType, String drugExposureTypeDesc, BigDecimal persistenceWindow) {
        this.drugExposureType = drugExposureType;
        this.drugExposureTypeDesc = drugExposureTypeDesc;
        this.persistenceWindow = persistenceWindow;
    }
    

   
    // Property accessors
    
    public String getDrugExposureType() {
        return this.drugExposureType;
    }
    
    public void setDrugExposureType(String drugExposureType) {
        this.drugExposureType = drugExposureType;
    }
    
    public String getDrugExposureTypeDesc() {
        return this.drugExposureTypeDesc;
    }
    
    public void setDrugExposureTypeDesc(String drugExposureTypeDesc) {
        this.drugExposureTypeDesc = drugExposureTypeDesc;
    }
    
    public BigDecimal getPersistenceWindow() {
        return this.persistenceWindow;
    }
    
    public void setPersistenceWindow(BigDecimal persistenceWindow) {
        this.persistenceWindow = persistenceWindow;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DrugExposureRefId) ) return false;
		 DrugExposureRefId castOther = ( DrugExposureRefId ) other; 
         
		 return ( (this.getDrugExposureType()==castOther.getDrugExposureType()) || ( this.getDrugExposureType()!=null && castOther.getDrugExposureType()!=null && this.getDrugExposureType().equals(castOther.getDrugExposureType()) ) )
 && ( (this.getDrugExposureTypeDesc()==castOther.getDrugExposureTypeDesc()) || ( this.getDrugExposureTypeDesc()!=null && castOther.getDrugExposureTypeDesc()!=null && this.getDrugExposureTypeDesc().equals(castOther.getDrugExposureTypeDesc()) ) )
 && ( (this.getPersistenceWindow()==castOther.getPersistenceWindow()) || ( this.getPersistenceWindow()!=null && castOther.getPersistenceWindow()!=null && this.getPersistenceWindow().equals(castOther.getPersistenceWindow()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDrugExposureType() == null ? 0 : this.getDrugExposureType().hashCode() );
         result = 37 * result + ( getDrugExposureTypeDesc() == null ? 0 : this.getDrugExposureTypeDesc().hashCode() );
         result = 37 * result + ( getPersistenceWindow() == null ? 0 : this.getPersistenceWindow().hashCode() );
         return result;
   }   





}
