package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 1, 2016 2:26:24 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.sql.Timestamp;


/**
 * Measurement generated by hbm2java
 */

public class Measurement {

	private int measurementId;
	private int personId;
	private int measurementConceptId;
	private Date measurementDate;
	private Timestamp measurementDateTime;
	private String measurementTime;
	private int measurementTypeConceptId;
	private Integer operatorConceptId;
	private BigDecimal valueAsNumber;
	private Integer valueAsConceptId;
	private Integer unitConceptId;
	private BigDecimal rangeLow;
	private BigDecimal rangeHigh;
	private Integer providerId;
	private Integer visitOccurrenceId;
	private String measurementSourceValue;
	private Integer measurementSourceConceptId;
	private String unitSourceValue;
	private String valueSourceValue;

	public Measurement() {
	}

	public Measurement(int measurementId, int personId,
			int measurementConceptId, Date measurementDate,
			int measurementTypeConceptId) {
		this.measurementId = measurementId;
		this.personId = personId;
		this.measurementConceptId = measurementConceptId;
		this.measurementDate = measurementDate;
		this.measurementTypeConceptId = measurementTypeConceptId;
	}

	public Measurement(int measurementId, int personId,
			int measurementConceptId, Date measurementDate, Timestamp measurementDateTime,
			String measurementTime, int measurementTypeConceptId,
			Integer operatorConceptId, BigDecimal valueAsNumber,
			Integer valueAsConceptId, Integer unitConceptId,
			BigDecimal rangeLow, BigDecimal rangeHigh, Integer providerId,
			Integer visitOccurrenceId, String measurementSourceValue,
			Integer measurementSourceConceptId, String unitSourceValue,
			String valueSourceValue) {
		this.measurementId = measurementId;
		this.personId = personId;
		this.measurementConceptId = measurementConceptId;
		this.measurementDate = measurementDate;
		this.measurementDateTime = measurementDateTime;
		this.measurementTime = measurementTime;
		this.measurementTypeConceptId = measurementTypeConceptId;
		this.operatorConceptId = operatorConceptId;
		this.valueAsNumber = valueAsNumber;
		this.valueAsConceptId = valueAsConceptId;
		this.unitConceptId = unitConceptId;
		this.rangeLow = rangeLow;
		this.rangeHigh = rangeHigh;
		this.providerId = providerId;
		this.visitOccurrenceId = visitOccurrenceId;
		this.measurementSourceValue = measurementSourceValue;
		this.measurementSourceConceptId = measurementSourceConceptId;
		this.unitSourceValue = unitSourceValue;
		this.valueSourceValue = valueSourceValue;
	}
      
                	public int getMeasurementId() {
		return this.measurementId;
	}
	public void setMeasurementId(int measurementId) {
		this.measurementId = measurementId;
	}

        	public int getPersonId() {
		return this.personId;
	}
	public void setPersonId(int personId) {
		this.personId = personId;
	}

        	public int getMeasurementConceptId() {
		return this.measurementConceptId;
	}
	public void setMeasurementConceptId(int measurementConceptId) {
		this.measurementConceptId = measurementConceptId;
	}

        	public Date getMeasurementDate() {
		return this.measurementDate;
	}
	public void setMeasurementDate(Date measurementDate) {
		this.measurementDate = measurementDate;
	}

	public Timestamp getMeasurementDateTime() {
		return this.measurementDateTime;
	} 

	public void setMeasurementDateTime(Timestamp measurementDateTime) {
		this.measurementDateTime = measurementDateTime;
	}

        	public String getMeasurementTime() {
		return this.measurementTime;
	}
	public void setMeasurementTime(String measurementTime) {
		this.measurementTime = measurementTime;
	}

        	public int getMeasurementTypeConceptId() {
		return this.measurementTypeConceptId;
	}
	public void setMeasurementTypeConceptId(int measurementTypeConceptId) {
		this.measurementTypeConceptId = measurementTypeConceptId;
	}

        	public Integer getOperatorConceptId() {
		return this.operatorConceptId;
	}
	public void setOperatorConceptId(Integer operatorConceptId) {
		this.operatorConceptId = operatorConceptId;
	}

        	public BigDecimal getValueAsNumber() {
		return this.valueAsNumber;
	}
	public void setValueAsNumber(BigDecimal valueAsNumber) {
		this.valueAsNumber = valueAsNumber;
	}

        	public Integer getValueAsConceptId() {
		return this.valueAsConceptId;
	}
	public void setValueAsConceptId(Integer valueAsConceptId) {
		this.valueAsConceptId = valueAsConceptId;
	}

        	public Integer getUnitConceptId() {
		return this.unitConceptId;
	}
	public void setUnitConceptId(Integer unitConceptId) {
		this.unitConceptId = unitConceptId;
	}

        	public BigDecimal getRangeLow() {
		return this.rangeLow;
	}
	public void setRangeLow(BigDecimal rangeLow) {
		this.rangeLow = rangeLow;
	}

        	public BigDecimal getRangeHigh() {
		return this.rangeHigh;
	}
	public void setRangeHigh(BigDecimal rangeHigh) {
		this.rangeHigh = rangeHigh;
	}

        	public Integer getProviderId() {
		return this.providerId;
	}
	public void setProviderId(Integer providerId) {
		this.providerId = providerId;
	}

        	public Integer getVisitOccurrenceId() {
		return this.visitOccurrenceId;
	}
	public void setVisitOccurrenceId(Integer visitOccurrenceId) {
		this.visitOccurrenceId = visitOccurrenceId;
	}

        	public String getMeasurementSourceValue() {
		return this.measurementSourceValue;
	}
	public void setMeasurementSourceValue(String measurementSourceValue) {
		this.measurementSourceValue = measurementSourceValue;
	}

        	public Integer getMeasurementSourceConceptId() {
		return this.measurementSourceConceptId;
	}
	public void setMeasurementSourceConceptId(Integer measurementSourceConceptId) {
		this.measurementSourceConceptId = measurementSourceConceptId;
	}

        	public String getUnitSourceValue() {
		return this.unitSourceValue;
	}
	public void setUnitSourceValue(String unitSourceValue) {
		this.unitSourceValue = unitSourceValue;
	}

        	public String getValueSourceValue() {
		return this.valueSourceValue;
	}
	public void setValueSourceValue(String valueSourceValue) {
		this.valueSourceValue = valueSourceValue;
	}

}
