package edu.pitt.dbmi.ohdsiv5.db;
// Generated Aug 25, 2010 7:48:41 AM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;


/**
 * ConceptSynonym generated by hbm2java
 */

public class ConceptSynonym  {


    // Fields    

     private BigDecimal conceptSynonymId;
     private BigDecimal conceptId;
     private String descriptionName;


    // Constructors

    /** default constructor */
    public ConceptSynonym() {
    }

    
    /** full constructor */
    public ConceptSynonym(BigDecimal conceptSynonymId, BigDecimal conceptId, String descriptionName) {
        this.conceptSynonymId = conceptSynonymId;
        this.conceptId = conceptId;
        this.descriptionName = descriptionName;
    }
    

   
    // Property accessors
        
    public BigDecimal getConceptSynonymId() {
        return this.conceptSynonymId;
    }
    
    public void setConceptSynonymId(BigDecimal conceptSynonymId) {
        this.conceptSynonymId = conceptSynonymId;
    }
    
    public BigDecimal getConceptId() {
        return this.conceptId;
    }
    
    public void setConceptId(BigDecimal conceptId) {
        this.conceptId = conceptId;
    }
    
    public String getDescriptionName() {
        return this.descriptionName;
    }
    
    public void setDescriptionName(String descriptionName) {
        this.descriptionName = descriptionName;
    }
   








}
