package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:38:53 PM by Hibernate Tools 3.1.0.beta4



/**
 * ConditionOccurrenceRef generated by hbm2java
 */

public class ConditionOccurrenceRef  {


    // Fields    

     private Long id;


    // Constructors

    /** default constructor */
    public ConditionOccurrenceRef() {
    }

    
    /** full constructor */
    public ConditionOccurrenceRef(Long id) {
        this.id = id;
    }
    

   
    // Property accessors
                                        
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
   








}
