package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:42:31 PM by Hibernate Tools 3.1.0.beta4



/**
 * DoiAncestor generated by hbm2java
 */

public class DoiAncestor  {


    // Fields    

     private Long id;


    // Constructors

    /** default constructor */
    public DoiAncestor() {
    }

    
    /** full constructor */
    public DoiAncestor(Long id) {
        this.id = id;
    }
    

   
    // Property accessors
                        
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
   








}
