package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:43:41 PM by Hibernate Tools 3.1.0.beta4



/**
 * DrugExposureRef generated by hbm2java
 */

public class DrugExposureRef  {


    // Fields    

     private DrugExposureRefId id;


    // Constructors

    /** default constructor */
    public DrugExposureRef() {
    }

    
    /** full constructor */
    public DrugExposureRef(DrugExposureRefId id) {
        this.id = id;
    }
    

   
    // Property accessors
                                
    public DrugExposureRefId getId() {
        return this.id;
    }
    
    public void setId(DrugExposureRefId id) {
        this.id = id;
    }
   








}
