package edu.pitt.dbmi.ohdsiv5.db;
// Generated Aug 25, 2010 12:48:10 PM by Hibernate Tools 3.1.0.beta4
// DEPRECATED 08.19.2014 jlj69
import java.math.BigDecimal;


/**
 * Mds2Id generated by hbm2java
 */

public class Mds2Id  {


    // Fields    

     private BigDecimal reportdate;
     private BigDecimal patientid;


    // Constructors

    /** default constructor */
    public Mds2Id() {
    }

    
    /** full constructor */
    public Mds2Id(BigDecimal reportdate, BigDecimal patientid) {
        this.reportdate = reportdate;
        this.patientid = patientid;
    }
    

   
    // Property accessors
    
    public BigDecimal getReportdate() {
        return this.reportdate;
    }
    
    public void setReportdate(BigDecimal reportdate) {
        this.reportdate = reportdate;
    }
    
    public BigDecimal getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(BigDecimal patientid) {
        this.patientid = patientid;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Mds2Id) ) return false;
		 Mds2Id castOther = ( Mds2Id ) other; 
         
		 return ( (this.getReportdate()==castOther.getReportdate()) || ( this.getReportdate()!=null && castOther.getReportdate()!=null && this.getReportdate().equals(castOther.getReportdate()) ) )
 && ( (this.getPatientid()==castOther.getPatientid()) || ( this.getPatientid()!=null && castOther.getPatientid()!=null && this.getPatientid().equals(castOther.getPatientid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getReportdate() == null ? 0 : this.getReportdate().hashCode() );
         result = 37 * result + ( getPatientid() == null ? 0 : this.getPatientid().hashCode() );
         return result;
   }   





}
