package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:43:59 PM by Hibernate Tools 3.1.0.beta4



/**
 * OmopConditionEra generated by hbm2java
 */

public class OmopConditionEra  {


    // Fields    

     private Long id;


    // Constructors

    /** default constructor */
    public OmopConditionEra() {
    }

    
    /** full constructor */
    public OmopConditionEra(Long id) {
        this.id = id;
    }
    

   
    // Property accessors
                                                                        
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
   








}
