package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:44:59 PM by Hibernate Tools 3.1.0.beta4



/**
 * OmopDrugEra generated by hbm2java
 */

public class OmopDrugEra  {


    // Fields    

     private Long id;


    // Constructors

    /** default constructor */
    public OmopDrugEra() {
    }

    
    /** full constructor */
    public OmopDrugEra(Long id) {
        this.id = id;
    }
    

   
    // Property accessors
                                                                
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
   








}
