package edu.pitt.dbmi.ohdsiv5.db;
// Generated Jun 15, 2010 5:47:01 PM by Hibernate Tools 3.1.0.beta4



/**
 * ProcOccurrenceRef generated by hbm2java
 */

public class ProcOccurrenceRef  {


    // Fields    

     private Long id;


    // Constructors

    /** default constructor */
    public ProcOccurrenceRef() {
    }

    
    /** full constructor */
    public ProcOccurrenceRef(Long id) {
        this.id = id;
    }
    

   
    // Property accessors
                                
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
   








}
