package edu.pitt.dbmi.ohdsiv5.db;

import java.util.List;

/**
 * SourceToConceptMap generated by hbm2java
 */

	public class SourceToConceptMap  {


	// Fields    

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer sourceToConceptMapId;
	private String sourceCode;
	private String sourceCodeDescription;
	private String mappingType;
	private Integer targetConceptId;
	private Integer targetVocabularyId;
	private Integer sourceVocabularyId;


	// Constructors

	/** default constructor */
	public SourceToConceptMap() {
	}

	/** minimal constructor */
	public SourceToConceptMap(String sourceCode, String mappingType, Integer targetConceptId, Integer targetVocabularyId, Integer sourceVocabularyId) {
		this.sourceCode = sourceCode;
		this.mappingType = mappingType;
		this.targetConceptId = targetConceptId;
		this.targetVocabularyId = targetVocabularyId;
		this.sourceVocabularyId = sourceVocabularyId;
	}

	/** full constructor */
	public SourceToConceptMap(String sourceCode, String sourceCodeDescription, String mappingType, Integer targetConceptId, Integer targetVocabularyId, Integer sourceVocabularyId) {
		this.sourceCode = sourceCode;
		this.sourceCodeDescription = sourceCodeDescription;
		this.mappingType = mappingType;
		this.targetConceptId = targetConceptId;
		this.targetVocabularyId = targetVocabularyId;
		this.sourceVocabularyId = sourceVocabularyId;
	}



	// Property accessors
			public String getSourceCode() {
		return this.sourceCode;
	}

	public void setSourceCode(String sourceCode) {
		this.sourceCode = sourceCode;
	}

	
	public String getSourceCodeDescription() {
		return this.sourceCodeDescription;
	}

	public void setSourceCodeDescription(String sourceCodeDescription) {
		this.sourceCodeDescription = sourceCodeDescription;
	}

	
	public String getMappingType() {
		return this.mappingType;
	}

	public void setMappingType(String mappingType) {
		this.mappingType = mappingType;
	}


		public Integer getTargetConceptId() {
		return this.targetConceptId;
	}

	public void setTargetConceptId(Integer targetConceptId) {
		this.targetConceptId = targetConceptId;
	}


	
	public Integer getTargetVocabularyId() {
		return this.targetVocabularyId;
	}

	public void setTargetVocabularyId(Integer targetVocabularyId) {
		this.targetVocabularyId = targetVocabularyId;
	}

		public Integer getSourceVocabularyId() {
		return this.sourceVocabularyId;
	}

	public void setSourceVocabularyId(Integer sourceVocabularyId) {
		this.sourceVocabularyId = sourceVocabularyId;
	}

}
